// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuZiHgP4PXZo-NCn3VJk3tNadKd5BxhpY',
    appId: '1:67802230616:web:4b748b2deddffa043fff2d',
    messagingSenderId: '67802230616',
    projectId: 'edupin-1e337',
    authDomain: 'edupin-1e337.firebaseapp.com',
    storageBucket: 'edupin-1e337.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvDohmv6YjinCBwx-mp45n-IVwHAYtBRA',
    appId: '1:67802230616:android:fb15e87685d540173fff2d',
    messagingSenderId: '67802230616',
    projectId: 'edupin-1e337',
    storageBucket: 'edupin-1e337.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8UExWNZmGP71Ipshr65ccqg2A0CB95Rg',
    appId: '1:67802230616:ios:3b91f8bf0e89c0113fff2d',
    messagingSenderId: '67802230616',
    projectId: 'edupin-1e337',
    storageBucket: 'edupin-1e337.firebasestorage.app',
    androidClientId: '67802230616-j7m8afujp0j8eqpqsqaodm36qfdtikmg.apps.googleusercontent.com',
    iosClientId: '67802230616-vebpep9q1fs661pckpn9jlpn9mblpahj.apps.googleusercontent.com',
    iosBundleId: 'com.example.edupin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8UExWNZmGP71Ipshr65ccqg2A0CB95Rg',
    appId: '1:67802230616:ios:3b91f8bf0e89c0113fff2d',
    messagingSenderId: '67802230616',
    projectId: 'edupin-1e337',
    storageBucket: 'edupin-1e337.firebasestorage.app',
    androidClientId: '67802230616-j7m8afujp0j8eqpqsqaodm36qfdtikmg.apps.googleusercontent.com',
    iosClientId: '67802230616-vebpep9q1fs661pckpn9jlpn9mblpahj.apps.googleusercontent.com',
    iosBundleId: 'com.example.edupin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCuZiHgP4PXZo-NCn3VJk3tNadKd5BxhpY',
    appId: '1:67802230616:web:bb6fad31710159a73fff2d',
    messagingSenderId: '67802230616',
    projectId: 'edupin-1e337',
    authDomain: 'edupin-1e337.firebaseapp.com',
    storageBucket: 'edupin-1e337.firebasestorage.app',
  );
}
